### ISSUE TITLE
Improve UI in file explorer 

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [kfichter/qmix-revamp#4]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/qtum-project/Lobby)
```

**Current behavior**
The action in file explore is hidden, so it will be hard for new users to use the application without explicit instruction.

**Expected behavior**
Have a actions bar displayed at top, so users can easily perform an action

**Comment by kfichter** [comment]
I added this in 098d862e027f86010a4283a9bc760c9ca0db76d1.
