### ISSUE TITLE
when you zoom in on qmix the UI breaks!

### ISSUE THREAD

**Issue by cjoshmartin** [kfichter/qmix-revamp#5]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/qtum-project/Lobby)
```

**Current behavior**

When I am in a web browser trying to run qmix, the UI will break if I try to zoom in on the text

**Comment by kfichter** [comment]
Thanks! Fixed in f151e53a29fd56ad126b320276f59d49ddb20dd9.
